-- Code generated by erm.
-- Initial schema migration.

CREATE TABLE IF NOT EXISTS users (
    id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id)
);

