// Code generated by erm. DO NOT EDIT.
package resolvers

import (
	"context"
	"fmt"
	"github.com/deicod/erm/graphql"
	"github.com/deicod/erm/graphql/dataloaders"
	"github.com/deicod/erm/graphql/relay"
	"github.com/deicod/erm/orm/gen"
)

type entityHooks struct {
	BeforeCreateUser func(ctx context.Context, r *Resolver, input graphql.CreateUserInput, model *gen.User) error
	AfterCreateUser  func(ctx context.Context, r *Resolver, record *gen.User) error
	BeforeUpdateUser func(ctx context.Context, r *Resolver, input graphql.UpdateUserInput, model *gen.User) error
	AfterUpdateUser  func(ctx context.Context, r *Resolver, record *gen.User) error
	BeforeDeleteUser func(ctx context.Context, r *Resolver, input graphql.DeleteUserInput, id string) error
	AfterDeleteUser  func(ctx context.Context, r *Resolver, input graphql.DeleteUserInput, id string) error
	BeforeReturnUser func(ctx context.Context, r *Resolver, record *gen.User) error
}

func (r *Resolver) applyBeforeCreateUser(ctx context.Context, input graphql.CreateUserInput, model *gen.User) error {
	if r == nil || r.hooks.BeforeCreateUser == nil {
		return nil
	}
	return r.hooks.BeforeCreateUser(ctx, r, input, model)
}

func (r *Resolver) applyAfterCreateUser(ctx context.Context, record *gen.User) error {
	if r == nil || record == nil || r.hooks.AfterCreateUser == nil {
		return nil
	}
	return r.hooks.AfterCreateUser(ctx, r, record)
}

func (r *Resolver) applyBeforeUpdateUser(ctx context.Context, input graphql.UpdateUserInput, model *gen.User) error {
	if r == nil || r.hooks.BeforeUpdateUser == nil {
		return nil
	}
	return r.hooks.BeforeUpdateUser(ctx, r, input, model)
}

func (r *Resolver) applyAfterUpdateUser(ctx context.Context, record *gen.User) error {
	if r == nil || record == nil || r.hooks.AfterUpdateUser == nil {
		return nil
	}
	return r.hooks.AfterUpdateUser(ctx, r, record)
}

func (r *Resolver) applyBeforeDeleteUser(ctx context.Context, input graphql.DeleteUserInput, id string) error {
	if r == nil || r.hooks.BeforeDeleteUser == nil {
		return nil
	}
	return r.hooks.BeforeDeleteUser(ctx, r, input, id)
}

func (r *Resolver) applyAfterDeleteUser(ctx context.Context, input graphql.DeleteUserInput, id string) error {
	if r == nil || r.hooks.AfterDeleteUser == nil {
		return nil
	}
	return r.hooks.AfterDeleteUser(ctx, r, input, id)
}

func (r *Resolver) applyBeforeReturnUser(ctx context.Context, record *gen.User) error {
	if r == nil || record == nil || r.hooks.BeforeReturnUser == nil {
		return nil
	}
	return r.hooks.BeforeReturnUser(ctx, r, record)
}

func (r *queryResolver) Node(ctx context.Context, id string) (graphql.Node, error) {
	typ, nativeID, err := relay.FromGlobalID(id)
	if err != nil {
		return nil, err
	}
	switch typ {
	case "User":
		record, err := r.loadUser(ctx, nativeID)
		if err != nil {
			return nil, err
		}
		if record == nil {
			return nil, nil
		}
		if err := r.applyBeforeReturnUser(ctx, record); err != nil {
			return nil, err
		}
		return toGraphQLUser(record), nil
	default:
		return nil, fmt.Errorf("unknown node type %s", typ)
	}
}

func (r *Resolver) loadUser(ctx context.Context, id string) (*gen.User, error) {
	if r == nil || r.ORM == nil {
		return nil, nil
	}
	if loaders := dataloaders.FromContext(ctx); loaders != nil {
		if loader := loaders.User(); loader != nil {
			return loader.Load(ctx, id)
		}
	}
	return r.ORM.Users().ByID(ctx, id)
}

func (r *Resolver) primeUser(ctx context.Context, record *gen.User) {
	if record == nil {
		return
	}
	if loaders := dataloaders.FromContext(ctx); loaders != nil {
		if loader := loaders.User(); loader != nil {
			loader.Prime(record.ID, record)
		}
	}
}

func toGraphQLUser(record *gen.User) *graphql.User {
	if record == nil {
		return nil
	}
	return &graphql.User{
		ID:        relay.ToGlobalID("User", record.ID),
		CreatedAt: record.CreatedAt,
		UpdatedAt: record.UpdatedAt,
	}
}

func decodeUserID(id string) (string, error) {
	if id == "" {
		return "", fmt.Errorf("id is required")
	}
	typ, nativeID, err := relay.FromGlobalID(id)
	if err != nil {
		return id, nil
	}
	if typ != "User" {
		return "", fmt.Errorf("invalid id for User: %s", typ)
	}
	return nativeID, nil
}

func (r *queryResolver) User(ctx context.Context, id string) (*graphql.User, error) {
	nativeID, err := decodeUserID(id)
	if err != nil {
		return nil, err
	}
	record, err := r.loadUser(ctx, nativeID)
	if err != nil {
		return nil, err
	}
	if err := r.applyBeforeReturnUser(ctx, record); err != nil {
		return nil, err
	}
	return toGraphQLUser(record), nil
}

func (r *queryResolver) Users(ctx context.Context, first *int, after *string, last *int, before *string) (*graphql.UserConnection, error) {
	if r.ORM == nil {
		return nil, fmt.Errorf("orm client is not configured")
	}
	if last != nil || before != nil {
		return nil, fmt.Errorf("backward pagination is not supported")
	}
	limit := defaultPageSize
	if first != nil && *first > 0 {
		limit = *first
	}
	offset := 0
	if after != nil && *after != "" {
		if decoded, err := decodeCursor(*after); err == nil {
			offset = decoded + 1
		}
	}
	total, err := r.ORM.Users().Count(ctx)
	if err != nil {
		return nil, err
	}
	records, err := r.ORM.Users().List(ctx, limit, offset)
	if err != nil {
		return nil, err
	}
	edges := make([]*graphql.UserEdge, len(records))
	for idx, record := range records {
		cursor := encodeCursor(offset + idx)
		if err := r.applyBeforeReturnUser(ctx, record); err != nil {
			return nil, err
		}
		r.primeUser(ctx, record)
		edges[idx] = &graphql.UserEdge{
			Cursor: cursor,
			Node:   toGraphQLUser(record),
		}
	}
	var startCursor, endCursor *string
	if len(edges) > 0 {
		sc := edges[0].Cursor
		ec := edges[len(edges)-1].Cursor
		startCursor = &sc
		endCursor = &ec
	}
	pageInfo := &graphql.PageInfo{
		HasNextPage:     offset+len(edges) < total,
		HasPreviousPage: offset > 0,
		StartCursor:     startCursor,
		EndCursor:       endCursor,
	}
	return &graphql.UserConnection{
		Edges:      edges,
		PageInfo:   pageInfo,
		TotalCount: total,
	}, nil
}

func (r *mutationResolver) CreateUser(ctx context.Context, input graphql.CreateUserInput) (*graphql.CreateUserPayload, error) {
	if r.ORM == nil {
		return nil, fmt.Errorf("orm client is not configured")
	}
	model := new(gen.User)
	if input.ID != nil {
		model.ID = *input.ID
	}
	if input.CreatedAt != nil {
		model.CreatedAt = *input.CreatedAt
	}
	if input.UpdatedAt != nil {
		model.UpdatedAt = *input.UpdatedAt
	}
	if err := r.applyBeforeCreateUser(ctx, input, model); err != nil {
		return nil, err
	}
	record, err := r.ORM.Users().Create(ctx, model)
	if err != nil {
		return nil, err
	}
	if err := r.applyAfterCreateUser(ctx, record); err != nil {
		return nil, err
	}
	if err := r.applyBeforeReturnUser(ctx, record); err != nil {
		return nil, err
	}
	gqlRecord := toGraphQLUser(record)
	r.primeUser(ctx, record)
	publishSubscriptionEvent(ctx, r.subscriptionBroker(), "User", SubscriptionTriggerCreated, gqlRecord)
	return &graphql.CreateUserPayload{
		ClientMutationID: input.ClientMutationID,
		User:             gqlRecord,
	}, nil
}

func (r *mutationResolver) UpdateUser(ctx context.Context, input graphql.UpdateUserInput) (*graphql.UpdateUserPayload, error) {
	if r.ORM == nil {
		return nil, fmt.Errorf("orm client is not configured")
	}
	nativeID, err := decodeUserID(input.ID)
	if err != nil {
		return nil, err
	}
	model := &gen.User{ID: nativeID}
	if input.CreatedAt != nil {
		model.CreatedAt = *input.CreatedAt
	}
	if input.UpdatedAt != nil {
		model.UpdatedAt = *input.UpdatedAt
	}
	if err := r.applyBeforeUpdateUser(ctx, input, model); err != nil {
		return nil, err
	}
	record, err := r.ORM.Users().Update(ctx, model)
	if err != nil {
		return nil, err
	}
	if err := r.applyAfterUpdateUser(ctx, record); err != nil {
		return nil, err
	}
	if err := r.applyBeforeReturnUser(ctx, record); err != nil {
		return nil, err
	}
	gqlRecord := toGraphQLUser(record)
	r.primeUser(ctx, record)
	publishSubscriptionEvent(ctx, r.subscriptionBroker(), "User", SubscriptionTriggerUpdated, gqlRecord)
	return &graphql.UpdateUserPayload{
		ClientMutationID: input.ClientMutationID,
		User:             gqlRecord,
	}, nil
}

func (r *mutationResolver) DeleteUser(ctx context.Context, input graphql.DeleteUserInput) (*graphql.DeleteUserPayload, error) {
	if r.ORM == nil {
		return nil, fmt.Errorf("orm client is not configured")
	}
	nativeID, err := decodeUserID(input.ID)
	if err != nil {
		return nil, err
	}
	if err := r.applyBeforeDeleteUser(ctx, input, nativeID); err != nil {
		return nil, err
	}
	if err := r.ORM.Users().Delete(ctx, nativeID); err != nil {
		return nil, err
	}
	if err := r.applyAfterDeleteUser(ctx, input, nativeID); err != nil {
		return nil, err
	}
	deletedID := relay.ToGlobalID("User", nativeID)
	publishSubscriptionEvent(ctx, r.subscriptionBroker(), "User", SubscriptionTriggerDeleted, deletedID)
	return &graphql.DeleteUserPayload{
		ClientMutationID: input.ClientMutationID,
		DeletedUserID:    deletedID,
	}, nil
}

func (r *subscriptionResolver) UserCreated(ctx context.Context) (<-chan *graphql.User, error) {
	stream, stop, err := subscribeToEntity(ctx, r.subscriptionBroker(), "User", SubscriptionTriggerCreated)
	if err != nil {
		return nil, err
	}
	out := make(chan *graphql.User, 1)
	go func() {
		defer close(out)
		if stop != nil {
			defer stop()
		}
		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-stream:
				if !ok {
					return
				}
				record, ok := payload.(*graphql.User)
				if !ok || record == nil {
					continue
				}
				select {
				case out <- record:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

func (r *subscriptionResolver) UserUpdated(ctx context.Context) (<-chan *graphql.User, error) {
	stream, stop, err := subscribeToEntity(ctx, r.subscriptionBroker(), "User", SubscriptionTriggerUpdated)
	if err != nil {
		return nil, err
	}
	out := make(chan *graphql.User, 1)
	go func() {
		defer close(out)
		if stop != nil {
			defer stop()
		}
		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-stream:
				if !ok {
					return
				}
				record, ok := payload.(*graphql.User)
				if !ok || record == nil {
					continue
				}
				select {
				case out <- record:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

func (r *subscriptionResolver) UserDeleted(ctx context.Context) (<-chan string, error) {
	stream, stop, err := subscribeToEntity(ctx, r.subscriptionBroker(), "User", SubscriptionTriggerDeleted)
	if err != nil {
		return nil, err
	}
	out := make(chan string, 1)
	go func() {
		defer close(out)
		if stop != nil {
			defer stop()
		}
		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-stream:
				if !ok {
					return
				}
				id, ok := payload.(string)
				if !ok || id == "" {
					continue
				}
				select {
				case out <- id:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}
