package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/deicod/erm/internal/orm/dsl"
)

func ensureMigrationsPlaceholder(root string, entities []Entity) error {
	dir := filepath.Join(root, "migrations")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	path := filepath.Join(dir, "001_initial.sql")
	if _, err := os.ReadFile(path); err == nil {
		return nil
	}
	sql := renderInitialMigration(entities)
	return writeFile(path, []byte(sql))
}

func renderInitialMigration(entities []Entity) string {
	buf := &bytes.Buffer{}
	buf.WriteString("-- Code generated by erm.\n")
	buf.WriteString("-- Initial schema migration.\n\n")
	sort.Slice(entities, func(i, j int) bool { return entities[i].Name < entities[j].Name })
	for _, ent := range entities {
		table := pluralize(ent.Name)
		buf.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", table))
		cols := make([]string, 0, len(ent.Fields))
		primaryCols := make([]string, 0, 1)
		for _, field := range ent.Fields {
			column := fieldColumn(field)
			colDef := fmt.Sprintf("    %s %s", column, fieldSQLType(field))
			if !field.Nullable {
				colDef += " NOT NULL"
			}
			if field.IsPrimary {
				primaryCols = append(primaryCols, column)
			}
			if field.HasDefaultNow {
				colDef += " DEFAULT now()"
			} else if field.DefaultExpr != "" {
				colDef += fmt.Sprintf(" DEFAULT %s", field.DefaultExpr)
			}
			if field.IsUnique {
				colDef += " UNIQUE"
			}
			cols = append(cols, colDef)
		}
		if len(primaryCols) > 0 {
			cols = append(cols, fmt.Sprintf("    PRIMARY KEY (%s)", strings.Join(primaryCols, ", ")))
		}
		buf.WriteString(strings.Join(cols, ",\n"))
		buf.WriteString("\n);\n\n")

		// Indexes
		for _, idx := range ent.Indexes {
			method := ""
			if idx.Method != "" {
				method = fmt.Sprintf(" USING %s", idx.Method)
			}
			unique := ""
			if idx.IsUnique {
				unique = " UNIQUE"
			}
			where := ""
			if idx.Where != "" {
				where = fmt.Sprintf(" WHERE %s", idx.Where)
			}
			cols := strings.Join(idx.Columns, ", ")
			buf.WriteString(fmt.Sprintf("CREATE%s INDEX IF NOT EXISTS %s ON %s%s (%s)%s;\n\n", unique, idx.Name, table, method, cols, where))
		}
	}
	return buf.String()
}

func fieldSQLType(field dsl.Field) string {
	switch field.Type {
	case dsl.TypeUUID:
		return "uuid"
	case dsl.TypeString:
		return "text"
	case dsl.TypeInt:
		return "bigint"
	case dsl.TypeFloat:
		return "double precision"
	case dsl.TypeBool:
		return "boolean"
	case dsl.TypeBytes:
		return "bytea"
	case dsl.TypeTime:
		return "timestamptz"
	case dsl.TypeJSON:
		return "jsonb"
	default:
		return "text"
	}
}
